In [3]:
import numpy as np

# ndarray数组

In [4]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
a.reshape(3,5) # 3行5列的数组

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
b = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 切片

In [14]:
print(b[0,1])
print(b[:,1])
print(b[:,1:2])
print(b[1:3,0:2])

1
[ 1  6 11]
[[ 1]
 [ 6]
 [11]]
[[ 5  6]
 [10 11]]


## 类型转换

In [16]:
vector = np.array(["1","2","3"])
vector = vector.astype(float)
print(vector)

[1. 2. 3.]


# 读取本地文件

In [8]:
nf1 = np.genfromtxt("./data/test.csv",delimiter = ",", skip_header = 1) # skip_header 不读取第一行
nf1

array([[ 1., nan, 11.],
       [ 2., nan, 22.],
       [ 3., nan, 33.]])

# axis表示行和列

In [18]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
b.sum(axis = 1) # axis = 1 计算的是行的和

array([10, 35, 60])

In [21]:
b.sum(axis = 0) # axis = 0 计算的是列的和

array([15, 18, 21, 24, 27])

# 替代值

运用布尔值来替换值

In [7]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [8]:
second_column_25 = matrix[:,1] == 25
second_column_25

array([False,  True, False])

In [9]:
matrix[second_column_25,1] = 1
matrix

array([[ 5, 10, 15],
       [20,  1, 30],
       [35, 40, 45]])